project:
  title: "WOR Rainfall Simulation"
  output-dir: docs
  type: "site"
  
execute: 
  freeze: true # re-render only when source changes
  cache: true
   
website:

  title: "Prairie Strips Impact on Transport of Antibiotic Resistance Indicators in Poultry Litter"

  sidebar:
    style: "docked"
    collapse-level: 2
    contents: 
      - 16S.qmd
      - ARGs.qmd
      - WaterFlow.qmd
      
  navbar: 
    background: primary
    search: true
    # title: "Quarto practice site"
    
    right: 
      - text: "GERMS Lab"
        href: http://germslab.org
    
    
format: 
  html: 
    theme: cosmo
    css: styles/styles.scss
    toc: true