project:
  title: "WOR Rainfall Simulation"
  output-dir: docs
  type: "site"
  
execute: 
  freeze: true # re-render only when source changes
  cache: true
   
site:

  sidebar:
    style: "docked"
    collapese-level: 2
    contents: 
      - ManuscriptWalkthrough.Rmd
      - 16S.qmd
      
  navbar: 
    background: primary
    search: true
    title: "Quarto practice site"
    
    right: 
      - text: "GERMS Lab"
        url: "http://germslab.org"
    
    
format: 
  html: 
    theme: cosmo
    css: styles/styles.scss
    toc: true